# Generated by Django 5.2 on 2025-05-11 20:06

import micro_mobility_device_tracker.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micro_mobility_device_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='owner_image',
            field=models.ImageField(blank=True, null=True, upload_to=micro_mobility_device_tracker.models.user_image_path),
        ),
    ]
